// Ex11Dictionary.Run();
// Ex12ConcurrentDictionary.Run();
// Ex21Queue.Run();
// Ex22ConcurrentQueue.Run();
// Ex23ProducerConsumerExample.Run();
// Ex31Stack.Run();
// Ex32ConcurrentStack.Run();
// Ex33Example.Run();
// Ex41List.Run();
// Ex42ConcurrentBag.Run();
// Ex43Example.Run();
Ex55Demo.Run();